Title = "baalajimaestro"
baseurl = "https://baalajimaestro.me"
languageCode = "en-us"
title = "baalajimaestro"
theme = "hello-friend-ng"
googleAnalytics = "UA-149264131-1"

[params]
  author = "Baalaji Balasubramani"
  homeSubtitle = "Just a dot."
  avatarurl = "https://avatars1.githubusercontent.com/u/34187410?s=460&v=4"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  keywords = "homepage, blog programming"
  contentTypeName = "posts"
  defaultTheme = "dark"
  copyright = "Copyrights Reserved. Maestro Creativescape"
  [params.logo]
    logoText     = "$ baalajimaestro"
    logoHomeLink = "/"
[languages]
    [languages.en]
      subtitle  = ""
      weight    = 1
      copyright = 'Maestro Creativescape'
[menu]
  [[menu.main]]
    name = "contact"
    weight = 0
    url = "/contact"
  [[menu.main]]
    name = "posts"
    weight = 4
    url = "/posts"
  [[menu.main]]
    name = "about me"
    weight = 1
    url = "/about"
  [[menu.main]]
    name = "drone"
    weight = 2
    url = "https://builds.baalajimaestro.me"
  [[menu.main]]
      name = "taiga"
      weight = 3
      url = "https://taiga.baalajimaestro.me"
[[params.social]]
      name = "GitHub"
      icon = "fab fa-github fa-2x"
      url = "https://github.com/baalajimaestro"
[[params.social]]
      name = "Twitter"
      icon = "fab fa-twitter fa-2x"
      url = "https://twitter.com/baalajimaestro"
[[params.social]]
      name = "Telegram"
      icon = "fab fa-telegram fa-2x"
      url = "https://t.me/baalajimaestro"
[[params.social]]
      name = "Reddit"
      icon = "fab fa-reddit fa-2x"
      url = "https://www.reddit.com/user/baalajimaestro"
[[params.social]]
      name = "Discord"
      icon = "fab fa-discord fa-2x"
      url = "https://discord.com/users/404797553272684555"
